# publish-atlas.ps1
# Pull-first, export CSV->JSON into Dashboard, validate, commit, push.
# Usage:
#   powershell -ExecutionPolicy Bypass -File .\publish-atlas.ps1 "C:\Users\rick\projects\Atlas"

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Fail([string]$msg) { Write-Host "ERROR: $msg" -ForegroundColor Red; exit 1 }
function Info([string]$msg) { Write-Host $msg -ForegroundColor Cyan }
function Ok([string]$msg) { Write-Host $msg -ForegroundColor Green }

$AtlasPath = $args[0]
if (-not $AtlasPath) {
  Fail 'Usage: powershell -ExecutionPolicy Bypass -File .\publish-atlas.ps1 "C:\Path\To\Atlas"'
}

$DashboardDataPath = "public\data"

# --- 0) Ensure we're in AtlasDashboard repo ---
$gitTop = (git rev-parse --show-toplevel 2>$null)
if (-not $gitTop) { Fail "Not inside a git repo. cd into AtlasDashboard first." }
Set-Location $gitTop
Info "Repo root: $gitTop"

if (-not (Test-Path (Join-Path $gitTop "public"))) { Fail "Missing public/ at repo root." }
$targetDataDir = Join-Path $gitTop $DashboardDataPath
if (-not (Test-Path $targetDataDir)) { Fail "Dashboard data dir not found: $targetDataDir" }

# Guard: no merge/rebase
$gitDir = (git rev-parse --git-dir)
if ((Test-Path (Join-Path $gitDir "rebase-merge")) -or (Test-Path (Join-Path $gitDir "rebase-apply")) -or (Test-Path (Join-Path $gitDir "MERGE_HEAD"))) {
  Fail "Git merge/rebase in progress. Finish it before publishing."
}

# Guard: clean before pull
$status = (git status --porcelain)
if ($status) { Fail "Working tree not clean BEFORE pull.`n$status" }

# --- 1) Pull first ---
Info "Pulling latest from origin/main (rebase)..."
git pull --rebase

$status = (git status --porcelain)
if ($status) { Fail "Working tree not clean AFTER pull.`n$status" }

# --- 2) Source directories in Atlas ---
$atlasRoot = (Resolve-Path $AtlasPath).Path
$latestAll = Join-Path $atlasRoot "data\output\latest\all"
$latestRisky = Join-Path $latestAll "risky"

if (-not (Test-Path $latestAll)) { Fail "Atlas latest/all not found: $latestAll" }
if (-not (Test-Path $latestRisky)) { Fail "Atlas latest/all/risky not found: $latestRisky" }

Info "Atlas latest/all:       $latestAll"
Info "Atlas latest/all/risky: $latestRisky"
Info "Dashboard target data:  $targetDataDir"

# --- 3) Helper: CSV -> JSON array of rows ---
function Export-CsvToJson([string]$csvPath, [string]$jsonPath) {
  if (-not (Test-Path $csvPath)) { Fail "Missing CSV: $csvPath" }
  $rows = Import-Csv -Path $csvPath
  $json = $rows | ConvertTo-Json -Depth 10
  Set-Content -Path $jsonPath -Value $json -Encoding UTF8
}

# --- 4) Export the 6 recommendation files ---
$exports = @(
  @{ csv = (Join-Path $latestAll "recommended_3leg.csv"); json = (Join-Path $targetDataDir "recommended_3leg_latest.json") }
  @{ csv = (Join-Path $latestAll "recommended_4leg.csv"); json = (Join-Path $targetDataDir "recommended_4leg_latest.json") }
  @{ csv = (Join-Path $latestAll "recommended_5leg.csv"); json = (Join-Path $targetDataDir "recommended_5leg_latest.json") }

  @{ csv = (Join-Path $latestRisky "recommended_3leg.csv"); json = (Join-Path $targetDataDir "risky_recommended_3leg_latest.json") }
  @{ csv = (Join-Path $latestRisky "recommended_4leg.csv"); json = (Join-Path $targetDataDir "risky_recommended_4leg_latest.json") }
  @{ csv = (Join-Path $latestRisky "recommended_5leg.csv"); json = (Join-Path $targetDataDir "risky_recommended_5leg_latest.json") }
)

Info ("Exporting {0} CSVs -> JSON..." -f $exports.Count)
foreach ($e in $exports) {
  Export-CsvToJson -csvPath $e.csv -jsonPath $e.json
}

# --- 5) Write status_latest.json (freshness + file list) ---
$filesStatus = @()
foreach ($e in $exports) {
  $j = Get-Item -Path $e.json
  $filesStatus += @{
    name = (Split-Path $e.json -Leaf)
    exists = $true
    bytes = $j.Length
    last_modified = $j.LastWriteTime.ToString("s")
  }
}

$statusObj = @{
  generated_at = (Get-Date).ToUniversalTime().ToString("s") + "Z"
  latest_dir = $latestAll
  ok = $true
  files = $filesStatus
  notes = "Generated by publish-atlas.ps1 from Atlas CSV outputs."
}

$statusJsonPath = Join-Path $targetDataDir "status_latest.json"
($statusObj | ConvertTo-Json -Depth 10) | Set-Content -Path $statusJsonPath -Encoding UTF8

# --- 6) Validate JSON (parse + conflict markers) ---
Info "Validating JSON integrity..."
$toValidate = @($exports.json + $statusJsonPath)
foreach ($p in $toValidate) {
  $raw = Get-Content -Path $p -Raw
  if ($raw -match '<<<<<<<|=======|>>>>>>>' ) { Fail "Merge conflict markers found: $p" }
  try { $null = $raw | ConvertFrom-Json } catch { Fail "Invalid JSON: $p`n$($_.Exception.Message)" }
}
Ok "JSON validation passed."

# --- 7) Commit + push if changes exist ---
git add $DashboardDataPath
$changes = (git diff --cached --name-only)
if (-not $changes) { Ok "No changes to publish. Exiting cleanly."; exit 0 }

$ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$msg = "Publish Atlas data ($ts)"
Info "Committing: $msg"
git commit -m $msg

Info "Pushing..."
git push

Ok "Publish complete. Cloudflare Pages will auto-deploy this commit."